"""create user table

Revision ID: fe48a18045b5
Revises: 
Create Date: 2026-02-25 12:51:12.050400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe48a18045b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Имя'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Фамилия'),
    sa.Column('surname', sa.String(length=100), nullable=False, comment='Отчество'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Почта'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Пароль'),
    sa.Column('role', sa.Enum('admin', 'manager', name='userrole'), server_default=sa.text("'manager'"), nullable=False, comment='Роль'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text("'false'"), nullable=False, comment='Удален ли пользователь'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
